services:
  db:
    image: mysql:8.0
    container_name: extension-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234!@#$
      MYSQL_DATABASE: extension_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - extension-network

networks:
  extension-network:
    driver: bridge